// <auto-generated />
using System;
using GestionProjet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionProjet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260311120109_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionProjet.Models.Affectation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeId")
                        .HasColumnType("int");

                    b.Property<int>("SousTacheId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeId");

                    b.HasIndex("SousTacheId");

                    b.ToTable("Affectations");
                });

            modelBuilder.Entity("GestionProjet.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("GestionProjet.Models.DeclarationTemps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DureeHeures")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("EmployeId")
                        .HasColumnType("int");

                    b.Property<int>("SousTacheId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeId");

                    b.HasIndex("SousTacheId");

                    b.ToTable("DeclarationsTemps");
                });

            modelBuilder.Entity("GestionProjet.Models.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("GroupeEquipeId")
                        .HasColumnType("int");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GroupeEquipeId");

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("GestionProjet.Models.GroupeEquipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TypeProjetCompatible")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("GroupesEquipe");
                });

            modelBuilder.Entity("GestionProjet.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeId")
                        .HasColumnType("int");

                    b.Property<bool>("Lu")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjetId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeId");

                    b.HasIndex("ProjetId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("GestionProjet.Models.Phase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("PourcentageBudget")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ProjetId")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TypePhase")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjetId");

                    b.ToTable("Phases");
                });

            modelBuilder.Entity("GestionProjet.Models.Projet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BudgetEstime")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BudgetReel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFinPrevue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFinReelle")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lieu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<string>("TypeProjet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DateDebut");

                    b.HasIndex("Statut");

                    b.ToTable("Projets");
                });

            modelBuilder.Entity("GestionProjet.Models.SousTache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DureeEstimeeHeures")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<int>("TacheId")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("TacheId");

                    b.ToTable("SousTaches");
                });

            modelBuilder.Entity("GestionProjet.Models.Tache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebutPrevue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFinPrevue")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhaseId")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.ToTable("Taches");
                });

            modelBuilder.Entity("GestionProjet.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTest")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeId")
                        .HasColumnType("int");

                    b.Property<int>("Resultat")
                        .HasColumnType("int");

                    b.Property<int>("TacheId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeId");

                    b.HasIndex("TacheId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("GestionProjet.Models.Affectation", b =>
                {
                    b.HasOne("GestionProjet.Models.Employe", "Employe")
                        .WithMany("Affectations")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionProjet.Models.SousTache", "SousTache")
                        .WithMany("Affectations")
                        .HasForeignKey("SousTacheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employe");

                    b.Navigation("SousTache");
                });

            modelBuilder.Entity("GestionProjet.Models.DeclarationTemps", b =>
                {
                    b.HasOne("GestionProjet.Models.Employe", "Employe")
                        .WithMany("DeclarationsTemps")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProjet.Models.SousTache", "SousTache")
                        .WithMany("DeclarationsTemps")
                        .HasForeignKey("SousTacheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employe");

                    b.Navigation("SousTache");
                });

            modelBuilder.Entity("GestionProjet.Models.Employe", b =>
                {
                    b.HasOne("GestionProjet.Models.GroupeEquipe", "GroupeEquipe")
                        .WithMany("Employes")
                        .HasForeignKey("GroupeEquipeId");

                    b.Navigation("GroupeEquipe");
                });

            modelBuilder.Entity("GestionProjet.Models.Notification", b =>
                {
                    b.HasOne("GestionProjet.Models.Employe", "Employe")
                        .WithMany("Notifications")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProjet.Models.Projet", null)
                        .WithMany("Notifications")
                        .HasForeignKey("ProjetId");

                    b.Navigation("Employe");
                });

            modelBuilder.Entity("GestionProjet.Models.Phase", b =>
                {
                    b.HasOne("GestionProjet.Models.Projet", "Projet")
                        .WithMany("Phases")
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("GestionProjet.Models.Projet", b =>
                {
                    b.HasOne("GestionProjet.Models.Client", "Client")
                        .WithMany("Projets")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("GestionProjet.Models.SousTache", b =>
                {
                    b.HasOne("GestionProjet.Models.Tache", "Tache")
                        .WithMany("SousTaches")
                        .HasForeignKey("TacheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tache");
                });

            modelBuilder.Entity("GestionProjet.Models.Tache", b =>
                {
                    b.HasOne("GestionProjet.Models.Phase", "Phase")
                        .WithMany("Taches")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phase");
                });

            modelBuilder.Entity("GestionProjet.Models.Test", b =>
                {
                    b.HasOne("GestionProjet.Models.Employe", "Employe")
                        .WithMany("TestsEffectues")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProjet.Models.Tache", "Tache")
                        .WithMany("Tests")
                        .HasForeignKey("TacheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employe");

                    b.Navigation("Tache");
                });

            modelBuilder.Entity("GestionProjet.Models.Client", b =>
                {
                    b.Navigation("Projets");
                });

            modelBuilder.Entity("GestionProjet.Models.Employe", b =>
                {
                    b.Navigation("Affectations");

                    b.Navigation("DeclarationsTemps");

                    b.Navigation("Notifications");

                    b.Navigation("TestsEffectues");
                });

            modelBuilder.Entity("GestionProjet.Models.GroupeEquipe", b =>
                {
                    b.Navigation("Employes");
                });

            modelBuilder.Entity("GestionProjet.Models.Phase", b =>
                {
                    b.Navigation("Taches");
                });

            modelBuilder.Entity("GestionProjet.Models.Projet", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Phases");
                });

            modelBuilder.Entity("GestionProjet.Models.SousTache", b =>
                {
                    b.Navigation("Affectations");

                    b.Navigation("DeclarationsTemps");
                });

            modelBuilder.Entity("GestionProjet.Models.Tache", b =>
                {
                    b.Navigation("SousTaches");

                    b.Navigation("Tests");
                });
#pragma warning restore 612, 618
        }
    }
}
